### ISSUE TITLE
Apprise cmdline test fails

### ISSUE THREAD

**Issue by JackDandy** [JackDandy/SickGear#16]
Hi @caronc

Failed to do a Windows test on cmd line...
```
... `apprise\apprise>python Apprise.py`

Traceback (most recent call last):
  File "Apprise.py", line 31, in <module>
    from .common import NotifyType
ValueError: Attempted relative import in non-package
```
Any ideas?

Thanks

**Comment by caronc** [comment]
You can't call `Apprise.py` directly like that.  You need to create a wrapper if you want to just use the library directly like that.
```bash
# install apprise
pip install apprise

#here you can use the apprise python file that gets installed
```

But if your goal is to use the library right after a git checkout, you can use the `bin/apprise` tool i ship with it:
```bash
git checkout https://github.com/caronc/apprise.git

# change to the recently cloned directory
cd apprise

# in windows, use the tool pre-package in the library:
python bin/apprise
```

If you want to use the library, you can [have a look at the `bin/apprise` file](https://raw.githubusercontent.com/caronc/apprise/master/bin/apprise) and you just need to set up the environment properly, and then you can directly use the module.  Alternatively, if you do a `pip install`, you can use the module right out of the gate.

**Comment by JackDandy** [comment]
Great, thanks @caronc
