### ISSUE TITLE
Asustor and Qnap

### ISSUE THREAD

**Issue by JackDandy** [JackDandy/SickGear#23]
Hi @clinton-hall

Hope you are well.

We made a couple major change to the SG repos this last month...

1) The default branch is now `main` (not `master`)
2) Python 3 is now the minimum required

Minor changes over the last few years since you published [Asustor packages,](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-Asustor) 
3) `requirements.txt` and `recommended.txt` are now in use

in checks, I saw a couple of potential issues and thought to reach out to you for help,

1) Maybe the Asustor package now fails due to 1+2 above.
2) The [Qnap package](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) you mentioned has not been updated, and someone reported it as failing

Your help is greatly appreciated, and if you can't look into the above, please help by letting me know so we can deprecate these.

JD

**Comment by clinton-hall** [comment]
Hi JD,

I have updated the Asustor apkg
https://www.dropbox.com/s/jzlmoig6l8aerem/sickgear_20230212_any.apk?dl=0

This installs the default branch, confirmed as main.
Python 3 was already used and requirements were installed. I have added recommended.

If you can share this link to users and have some test, I can submit this to app central once verified.

I’ll need to have a play with QNAP. I’ll try and look at it this week,

Regards,

Clinton

From: ***@***.***>
Sent: Sunday, February 12, 2023 12:17 PM
To: ***@***.***>
Cc: Clinton ***@***.***>; ***@***.***>
Subject: [JackDandy/SickGear] Asustor and Qnap (Issue #23)


Hi @clinton-hall<https://github.com/clinton-hall>

Hope you are well.

We have made a couple major change to the SG repos this last month...

  1.  The default branch is now main (not master)
  2.  Python 3 is now the minimum required

Minor changes over the last few years since you published Asustor packages,<https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-Asustor>
3) requirements.txt and recommended.txt are now in use

in checks, I saw a couple of potential issues and thought to reach out to you for help,

  1.  Maybe the Asustor package now fails due to 1+2 above.
  2.  The Qnap package<https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP> you mentioned has not been updated, and someone reported it as failing

Your help is greatly appreciated, and if you can't look into the above, please help by letting me know so we can deprecate these.

JD

**Comment by JackDandy** [comment]
Oh fantastic, thank you @clinton-hall

**Comment by JackDandy** [comment]
The Asustor version has been verified to be working as expected, all good.

**Comment by clinton-hall** [comment]
Asustor APKG has been submitted to App Central. Hopefully this should be approved in a few days and appear in the central repository.

I have started with the QNAP package. So far I have it running, but I still need to update my QNAP firmware to test on later versions (and I don't think the icons are linking properly on the desktop).

Anyone wanting to try can use this qpkg https://www.dropbox.com/s/kg3b6y556223c7s/SickGear_0.22.0.qpkg?dl=0

Note you first need to install `Entware-std` from the QNAP Club Store (https://qnapclub.eu/en/qpkg/556)

**Comment by JackDandy** [comment]
curious, is that package based on SG version 0.22.0 as its filename suggests?

If yes, SG is now at 3.xx.x range

**Comment by clinton-hall** [comment]
I took the existing QNAPClub qpkg which was 0.21.3 and I just increased the version slightly.
The idea is that an existing user should be able to upgrade. This uses the same ports and config etc.

So the version of the app is not related to the version of SG. SG will update within the app.

For dependency, I used Entware and this will install the latest python3 as well as the latest git. It does a git clone of latest SG, creates a python venv and installs all requirements and recommended via PIP.

The main reason I did it this way was to avoid too many required apkgs when there are different versions (and naming conventions) of python and git apps for QNAP.

**Comment by JackDandy** [comment]
> So the version of the app is not related to the version of SG. SG will update within the app.

Glad I asked, so yeah the originally was indeed related, the package version was equal to the SG version it was cut from.

These days, people will see the '3' in `3.xx.x`, and simply consider `0.22.x` old/legacy before even trying it. So it would be better and clearer to at least cut from latest version, and 3.xx.x is actually a divergence from the 0.xx.x repo. Perhaps, put a note in the readme that this is a major release from 0.xx to 3.xx in line with SG versioning, and is a drop in upgrade for 0.21.3.  

It's great that SG package upgrades past the base package version, even more awesome that `git` and `Python3` is bundled with your use of Entware -- brilliant.

**Comment by clinton-hall** [comment]
ok I have repackaged as 3.0.0 and added details in the description to explain that it auto updates.
The icons now display and everything appears to work for me.

I can't test QTS 5 as my QNAPs are obsolete! I'll have to leave this up to users to test (but as long as Entware can be installed, this app should work).

 https://www.dropbox.com/s/ss5ipcgoasa8d6k/SickGear_3.0.0.qpkg?dl=0

**Comment by JackDandy** [comment]
I have put out a request for someone to check newer firmware, fingers crossed.

Can you navigate to the SickGear `config/General/Misc/Updates`, make sure that both "`display...`" + "`include in 'Check for Updates' menu action`" is enabled in the "`Packages updates`" section, then perform a "`Check updates`" from the top right menu, and follow prompts to update. Then go back to config/General... `Package updates`, and dump what Python version and packages are listed there...

You should see something like this example from Windows...

<img src="https://i.vgy.me/1wEIoz.png">

Thanks again

**Comment by clinton-hall** [comment]
![image](https://user-images.githubusercontent.com/1888006/218837496-8707e808-8435-416e-bb4a-2a76c2a994d9.png)

On each start of the APKG itself it performs a git pull, and checks requirements + recommended via pip, so it should always be on the latest.

**Comment by JackDandy** [comment]
> On each start of the APKG itself

Am I right in thinking that "_each start_" is step 2, and not the steps 3 + 4 [here](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP)

Maybe these steps are not even correct, I am blind here.

**Comment by clinton-hall** [comment]
Yes step 3.

Starting the application via app centre should do a git pull.

So to do an update, disable the qpkg, then enable again.

I'll check again tonight but the internal updater gave a message to say the update can't acess something within the venv. I just realised I do the git pull after activating the venv and I suspect this may cause git to fail to update.

I'll move the git pull to happen before activating the venv. This should help ensure the source update works. Then activate venv and do the required pip checks/install.

This previous process worked on Asustor using git App (/usr/bin/git). But now that I use git via entware (/opt/bin/git) I suspect the git config is in a location that is not accessible by the venv...

**Comment by clinton-hall** [comment]
ok. I have switched the order and verified that it is updating via git on each start.
now version 3.0.1
https://www.dropbox.com/s/9eoqzfilba222pv/SickGear_3.0.1.qpkg?dl=0

**Comment by JackDandy** [comment]
So, if I need to add something to the QNAP page to say that SG internal update system doesn't work with this set-up, right?

**Comment by clinton-hall** [comment]
Short Version: Probably worth saying that if there are any issues updating to stop and start via the QNAP App Center.

Long Version:
It may update internally (I'm not 100% convinced that there is an issue with git. I got distracted by another issue and made the changes suggested previously. I feel this is a better way to do it, with the git pull outside of the venv).

The issue I got distracted by was the internal updater giving a warning about not being able to do the `--user` install/upgrade using pip within the venv.

So any changes of python modules due to a change in requirements.txt would likely fail using the internal updater, but I believe the actual SG git update works fine.

**Comment by JackDandy** [comment]
> any changes of python modules due to a change in requirements.txt would likely fail using the internal updater

I pushed a [hotfix](https://github.com/SickGear/SickGear/releases/tag/release_3.27.4) for this. It should now allow to update internally just fine, (the `--user` arg is not applicable to a venv), this means you should be able remove the git update on startup and SG will fully handle that as per the user configuration. This is easily tested by doing a pip uninstall of say `regex`.

**Comment by clinton-hall** [comment]
ok.... I have removed the git pull from start-up routines.

This allows both SickGear and Python modules to be updated within SG. So seems like a good setup now.

https://www.dropbox.com/s/5xp2jjymlpbhcaj/SickGear_3.0.2.qpkg?dl=0

The only question now is if this is going to be compatible with all models/Firmware versions. I can't test any other combinations at my end.

**Comment by JackDandy** [comment]
> So seems like a good setup now.

Yeah, with it now passing tests on your kit to be self-sufficient, It should be on a good footing.

>  The only question now ... 

Yeah, hopefully it wont take long for some feedback on other systems.

**Comment by JackDandy** [comment]
Hiya, just to let you know, we got a confirmed v5 sighting, 5.0.0.2055.

**Comment by clinton-hall** [comment]
> Hiya, just to let you know, we got a confirmed v5 sighting, 5.0.0.2055.

Great news. hopefully there are no issues, but let me know if something comes up.

**Comment by JackDandy** [comment]
Hi @clinton-hall 

Just a quickie, first we have had feedback to QNAP 5.0.1.2277 - good times.

I see lots of files at [entware](https://bin.entware.net/x64-k3.2/), i just want to verify that when a user elects to install entware on their QNAS, that all entwares packages are indeed installed as one, or does the user need to be made aware that they need to select to install `git` and  `python3` using some other menu?

Thank you.

**Comment by clinton-hall** [comment]
@JackDandy 
Glad to hear this appears to be working on QNAP.

Entware is essentially another package manager. Very few packages are installed when Entware is installed. Rather a command line tool `opkg` is installed. Users can install any available package using `opkg install` e.g. `opkg install python3` and `opkg install git`

When the SickGear qpkg is installed, this requires that Entware be installed first. As part of the package installation this will install the needed Entware packages.

So no, users don't need to do any other installation.

I also have some checks in the start-up script toe check the specific python version. So if a user does do a (manual) `opkg update python3` and move to a later version of python then the script should detect that the Entware version of python is different to the venv and in this case it should create a new venv for the new python version and install the needed modules via pip.

Part of the startup checks.
```
	cd $PKG_DIR

	# build venev if it doesn't exist
	[ -f $PKG_DIR/env/bin/activate ] || CreateVenv

	# build new venv if different py version
	python_version="$($PYTHON --version | sed 's/Python //g')"
	venv_version="$(cat env/pyvenv.cfg | grep version | sed 's/version = //g')"
	[ "$python_version" = "$venv_version" ] || CreateVenv

	# activate venv and install requirements
	source env/bin/activate

	cd $PKG_DIR/$PKG_NAME 
	python -m pip install -r requirements.txt
	python -m pip install -r recommended.txt 
```

the CreateVenev itself

```
CreateVenv() {
	cd $PKG_DIR
	ARCH=$(/bin/uname -m)
	if [ "$ARCH" = "x86_64" ]; then
		HEADER="http://bin.entware.net/x64-k3.2/include/include.tar.gz"
	elif [ "$ARCH" = "armv7l" ]; then
		HEADER="http://bin.entware.net/armv7sf-k3.2/include/include.tar.gz"
	elif [ "$ARCH" = "aarch64" ]; then      
        		HEADER="http://bin.entware.net/aarch64-k3.10/include/include.tar.gz"
	else
		HEADER="http://bin.entware.net/x86-k2.6/include/include.tar.gz"		
	fi
	/bin/echo -n " Creating new virtual environment"
	# Install these if not already present.
	/opt/bin/opkg update
	/opt/bin/opkg install python3
	/opt/bin/opkg install python3-pip
	/opt/bin/opkg install python3-cffi
	/opt/bin/opkg install python3-cryptography
	python_version="$($PYTHON --version | sed 's/Python //g')"
	py1="$(echo $python_version | cut -d'.' -f1)"
	py2="$(echo $python_version | cut -d'.' -f2)"
	wget -qO- $HEADER | tar xvz -C /opt/include
	$PYTHON -m pip install --upgrade pip
	$PYTHON -m pip install --user virtualenv
        # create venv without pip due to entware pip issues.
	$PYTHON -m venv --clear --without-pip env
	# copy existing lib packgaes to venev
	cp -rf /opt/lib/python${py1}.${py2}/site-packages/* env/lib/python${py1}.${py2}/site-packages/
        # activate venev
        source env/bin/activate
        # Within it, invoke this well-known script to manually install pip(1) into env
        curl https://bootstrap.pypa.io/get-pip.py | python
        deactivate
        # Reactivate now including the pip(1) command.
        source env/bin/activate
        # And finally, upgrade pip(1) itself  
        python -m pip install --upgrade pip
        deactivate		
}
```

**Comment by JackDandy** [comment]
That's proper thorough and fills my understanding,
thank you, much appreciation. ❤️
