### ISSUE TITLE
Choco package

### ISSUE THREAD

**Issue by JackDandy** [JackDandy/SickGear#5]
Hi @JourneyOver

I was looking at Choco [AU packagers](https://github.com/majkinetor/au/wiki/AU-In-Use) and saw your collection focuses on automation tools of the type that is SickGear.

Of the Sick* folks, SickGear is differentiated with a focus on fostering a rock solid tool for ourselves and our user-base since 2014. I invite you to scan the main repo issue and commit tracker to get a feel to its quality.  Can I ask if you would kindly consider making a Choco AU package for SickGear. I understand if it's not something for you, but thought I'd give it a go and ask.  Anyway, thanks for considering.

JackDandy

**Comment by JourneyOver** [comment]
I'll look into it, but it'll have to wait till I can get access to a computer again or mine is repaired (should hopefully be back up and running within 2 weeks as I have a Mobo/CPU coming in the replace broken ones) 

If you feel like you can't wait though you are free to always send a PR to my repository, just take a look at some of my other chocolatey packages in my repository to get a feel on how things should look, all you'll mainly need to make sure of if you go this route is to test things first, and second set the version in the nuspec to 0 when you send the PR so that it'll automatically grab the information for the latest release of sickrage and push it up since I'm unable to push brand new packages due to me not having a computer atm.

Though you are free to wait till I can get back up and running again with a computer and ill do everything myself as well

**Comment by JackDandy** [comment]
Sorry to hear about your computer woes, it's truly a pain when that happens for sure. 

> if you do decide to wait till I can do everything myself I will need to at least know of any requirements/silent install method (if there is any) as well

There's no rush, and a real plus that you can do everything once your systems are back in tip top form. Our well tested install steps are [here](https://github.com/SickGear/SickGear/wiki/Install-SickGear-[1]-Windows) with post-install speedup steps [here](https://github.com/SickGear/SickGear/wiki/Installation-Instructions#post-install-speedups), there are even a couple of defaults you could add to an initial config.ini that are listed after post install steps to make things even nicer/prettier for people, I can supply those when ready :)

So that leaves me to say, thank you!

**Comment by JourneyOver** [comment]
Will be taking a crack at creating this package within the next couple of days when I have free time, as I am now back up and running with a computer again.

**Comment by JourneyOver** [comment]
Sorry that I haven't really looked into making this a chocolatey package yet, some stuff came up irl (my mom ended up killing herself last week so these past two weeks has been kinda egh and I haven't really felt like doing a whole lot of anything) I can't really say when I'll get around to this yet, but I will eventually.

**Comment by JackDandy** [comment]
Oh forget all about this stuff, it really is no problem.

**Comment by JackDandy** [comment]
Hi @JourneyOver 

Everything looks sterling like Archer!

Just a few observations after a visual code review,

-  is git in env path and therefore usable by SG after install, can test by switching to dev branch in settings General/Advanced
- in file sickgear.nuspec `version = 0.0` -- is that the version of the installer or the SickGear release?
- is it possible to use `pip install -r requirements.txt` in dir of unpacked SG instead of "pip install Cheetah3>=3.1.0"
- replace 3 * ChocolateyShortCut `SickBeard.py` with `sickgear.py` (I've now updated Wiki pages around this change)
- Prob not an issue, should the case of Uninstall -> shortcutName be `SickGear.lnk` to match the install.ps1?
  
Can I test the install/uninstall flows from here before merge somehow ?

**Comment by JourneyOver** [comment]
https://mega.nz/#!5Fk0lI4C!tMtLBwT53sBVjqyo3dmKdeDwiFw2BAe9jW38fjefxCg

@JackDandy uploaded it to mega.nz due to the fact that github doesn't support .nupkg file types.

Anyways make sure you have chocolatey installed on the machine you plan on testing with, then cd into where you have the .nupkg file, and then `cinst sickgear -source %cd%` to test install, and then to test uninstall just do `cuninst sickgear`.

**Comment by JourneyOver** [comment]
@JackDandy so...from the looks of things, changing to the `pip install -r requirements.txt` for `Cheetah3>=3.1.0` is not going to be an option possibly, as doing so seems to now make the install throw an error (which means the above .nupkg file will more than likley throw an error as well when you try to test it..

This is the error it throws when it gets to the `pip install -r requirements.txt` part of the script.
```
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```
which can be seen in this test here https://ci.appveyor.com/project/JourneyOver/chocolatey-packages/builds/21855393 

if I comment out the `pip install -r requirements.txt` and put it back into the original pip install things work just fine which can be seen in this test here https://ci.appveyor.com/project/JourneyOver/chocolatey-packages/builds/21855680

so now the question is what you want me to do about this?

**Comment by JourneyOver** [comment]
@JackDandy 	let me know when you have been able to test install/uninstall.. and if you want me to add/change anything else.

**Comment by JackDandy** [comment]
@JourneyOver great, yup, I will do, thanks

**Comment by JourneyOver** [comment]
@JackDandy 	Changed up a bit since the above file so here is the new one https://mega.nz/#!MJNBTaTB!xtXZ_RA-BMe5vqlpFgHmwVTkK-5LLLIUe6OwmrlM-fw

**Comment by JackDandy** [comment]
@JourneyOver 
```
PS path.to\chocolately\SickGear\current> cinst sickgear -source %cd%
Chocolatey v0.10.11
Installing the following packages:
sickgear
By installing you accept licenses for the packages.
sickgear not installed. The package was not found with the source(s) listed.
 Source(s): '%cd%'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
```
tried appending `--pre` = also failed.
do you know what i'm doing wrong?

**Comment by JackDandy** [comment]
@JourneyOver 
In an admin powershell window...
```
PS path.to\chocolately\SickGear\current> cinst sickgear -source %cd%
Chocolatey v0.10.11
Installing the following packages:
sickgear
By installing you accept licenses for the packages.
sickgear not installed. The package was not found with the source(s) listed.
 Source(s): '%cd%'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
```

So in a admin command shell window 
```
path.to\chocolately\SickGear\current>cinst sickgear -source %cd%
Chocolatey v0.10.11
Installing the following packages:
sickgear
By installing you accept licenses for the packages.
sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.
sickgear package files install completed. Performing other installation steps.
The install of sickgear was NOT successful.
sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - sickgear (exited 1) - sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
https://chocolatey.org/compare
```
in both windows, tried appending `--pre` = this also failed.

do you know what i'm doing wrong?

**Comment by JackDandy** [comment]
@JourneyOver 

So in an admin command shell window 
```
path.to\chocolately\SickGear\current>cinst sickgear -source %cd%
Chocolatey v0.10.11
Installing the following packages:
sickgear
By installing you accept licenses for the packages.
sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.
sickgear package files install completed. Performing other installation steps.
The install of sickgear was NOT successful.
sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - sickgear (exited 1) - sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
https://chocolatey.org/compare
```
tried appending `--pre` = this also failed.

do you know what i'm doing wrong?

**Comment by JackDandy** [comment]
@JourneyOver 

So in an `Administrator Command Prompt` window 
```
path.to\chocolately\SickGear\current>cinst sickgear -source %cd%
Chocolatey v0.10.11
Installing the following packages:
sickgear
By installing you accept licenses for the packages.
sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.
sickgear package files install completed. Performing other installation steps.
The install of sickgear was NOT successful.
sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - sickgear (exited 1) - sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git.install (= 2.20.1)'.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
https://chocolatey.org/compare
```
I tried appending `--pre` but this also failed.

Any ideas?

**Comment by JourneyOver** [comment]
2 things.

1. Can you send me the chocolatey.log please? very strange that it's throwing a `unable to resolve dependency` error for you when it seems to work fine through install/uninstall testing on appveyor.

2. Can you test with this one here https://mega.nz/#!Ud9B2KLJ!OSzricYfGMBFa7uifAEGxgtpz7iXc57duWaryZIR7m4 and see if it works for you or not.

**Comment by JourneyOver** [comment]
@JackDandy 	

2 things.

1. Can you send me the chocolatey.log please? very strange that it's throwing a `unable to resolve dependency` error for you when it seems to work fine through install/uninstall testing on appveyor.

2. Can you test with this one here https://mega.nz/#!Ud9B2KLJ!OSzricYfGMBFa7uifAEGxgtpz7iXc57duWaryZIR7m4 and see if it works for you or not.

**Comment by JackDandy** [comment]
(2) Fails; the log included below...

(1) Anonymized chocolatey.log...
```
2019-01-25 09:51:47,571 45780 [DEBUG] - XmlConfiguration is now operational
2019-01-25 09:51:47,624 45780 [INFO ] - ============================================================
2019-01-25 09:51:47,845 45780 [INFO ] - Chocolatey v0.10.11
2019-01-25 09:51:47,854 45780 [DEBUG] - Chocolatey is running on Windows v 10.0.14393.0
2019-01-25 09:51:47,857 45780 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2019-01-25 09:51:47,858 45780 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2019-01-25 09:51:47,887 45780 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install sickgear -source %path.to%\chocolately\SickGear\current
2019-01-25 09:51:47,889 45780 [DEBUG] - Received arguments: install sickgear -source %path.to%\chocolately\SickGear\current
2019-01-25 09:51:47,946 45780 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2019-01-25 09:51:47,953 45780 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2019-01-25 09:51:47,962 45780 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2019-01-25 09:51:48,027 45780 [DEBUG] - The source '%path.to%\chocolately\SickGear\current' evaluated to a 'normal' source type
2019-01-25 09:51:48,029 45780 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple 
 check to be sure no sensitive data is shown, especially if copying 
 output to a gist for review.
2019-01-25 09:51:48,041 45780 [DEBUG] - Configuration: CommandName='install'|
CacheLocation='C:\Users\%user%\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='%path.to%\chocolately\SickGear\current'|

SourceType='normal'|Debug='False'|Verbose='False'|Trace='False'|
Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='sickgear'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='sickgear'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.14393.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.11.0'|
Information.ChocolateyProductVersion='0.10.11'|
Information.FullName='choco, Version=0.10.11.0, Culture=neutral, PublicKeyToken=79d02...'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='%user%'|
Information.UserDomainName='%computer.name%'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
PinCommand.Command='unknown'|OutdatedCommand.IgnorePinned='False'|
Proxy.BypassOnLocal='True'|
2019-01-25 09:51:48,042 45780 [DEBUG] - _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
2019-01-25 09:51:48,048 45780 [INFO ] - Installing the following packages:
2019-01-25 09:51:48,050 45780 [INFO ] - sickgear
2019-01-25 09:51:48,050 45780 [INFO ] - By installing you accept licenses for the packages.
2019-01-25 09:51:48,240 45780 [INFO ] - [NuGet] Attempting to resolve dependency 'git (= 2.20.1)'.
2019-01-25 09:51:48,252 45780 [ERROR] - sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git (= 2.20.1)'.
2019-01-25 09:51:48,261 45780 [INFO ] - sickgear package files install completed. Performing other installation steps.
2019-01-25 09:51:48,265 45780 [DEBUG] - No package information as package is null.
2019-01-25 09:51:48,288 45780 [DEBUG] - No package information to save as package is null.
2019-01-25 09:51:48,290 45780 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2019-01-25 09:51:48,291 45780 [ERROR] - The install of sickgear was NOT successful.
2019-01-25 09:51:48,296 45780 [ERROR] - sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git (= 2.20.1)'.
2019-01-25 09:51:48,312 45780 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2019-01-25 09:51:48,316 45780 [INFO ] - 
2019-01-25 09:51:48,318 45780 [ERROR] - Failures
2019-01-25 09:51:48,321 45780 [ERROR] -  - sickgear (exited 1) - sickgear not installed. An error occurred during installation:
 Unable to resolve dependency 'git (= 2.20.1)'.
2019-01-25 09:51:48,324 45780 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2019-01-25 09:51:48,330 45780 [DEBUG] - Exiting with 1
```
further, from regular `Command Prompt`...
```
> git.exe --version
git version 2.20.1.windows.1
```
I'm unsure if having `git` already installed is causing the issue, however, I'd expect the choco git dep. installer to skip installation if it determined that an installed version is the same as the one it has to install.  So putting that thought aside, the choco log reports a failure to find the dependency which is something different.  This is proving a worthy test.

**Comment by JourneyOver** [comment]
@JackDandy 	

I think I see the reason why it's failing for you, but idk why it's doing it for you but not for me exactly..

For some reason or another it's not pulling in the chocolatey API for you so therfor it can't see any possible packages other than just well the sickgear package, so it can't see the dependency packages either which is why it can't resolve them.

So let's try this and see if it works instead; instead of doing `cinst sickgear -source %cd%` can you try `cinst sickgear -source %cd%;chocolatey` instead and see if that resolves it for you.

short of that, if that doesn't work for you either, then the only other option I have really is just going about finishing up the package and merging it into my master branch so it can get updated/pushed up to chocolatey, and then once the package is actually on chocolatey, things should work like any normal chocolatey package.

**Comment by JackDandy** [comment]
It seems to be working, but not checking pre-installed git which is sub-optimal, but I understand that that's not in your control.

**Comment by JourneyOver** [comment]
Great glad to hear :D and yea sadly that is not something I am able to do anything about as I do not control the git package otherwise I would. Anyways test install/uninstall and all that and if there is anything you want me to add/change let me know and I will get to it once I wake up as I'm heading to bed now since it's 5AM >.< so have a goodnight ^^

**Comment by JackDandy** [comment]
Hi @JourneyOver 

I can see two important issues to address...

1. Starting SickGear at Windows startup
The listed `Method 2` (registry) will work for w10 and older [here](https://windowsreport.com/remove-startup-apps-windows-10/) and of course, this system change would be added to `uninstall.ps1`

2. Installing SickGear
Many systems (incl. mine) have `Python` already installed (mine into a path other than C:\Python27) and available via the system environment path. But this is completely ignored by the current choco package installer, this is all kinds of bad. In particular... a) existing Python installed applications and their respective deps get broken, and b) the Add/Remove Programs Uninstall for the pre-existing Python is destroyed. 
Ok, that's the bad, now, an idea on how to move forward... Instead of using the sickgear.nuspec `dependencies` entity, can `python` and `git` be moved into the `chocolateyInstall.ps1` file so that logic capability to find installed versions linked to a conditional install can be achieved. The `SickGear.lnk` desktop shortcut `Target` and `Start in` fields would be created with the path to potential existing Python - provided that the version of the existing python is 2.7.9 or higher ***and*** less than 3.0 (having this logic will also make things easier to manage when SG becomes Python3 compatible) -- and if version condition is not satisfied, then the known dependency can then be fetched (bandwidth saved) and installed as default.

**Comment by JourneyOver** [comment]
@JackDandy 	

> Starting SickGear at Windows startup
> The listed Method 2 (registry) will work for w10 and older here and of course, this system change would need adding to uninstall.ps1

The install script should be adding both a shortcut both at the desktop, and in the startup folder as followed through by https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B1%5D-Windows#note-do-not-use-vbs-scripts-to-start-sg-theyre-a-100-nonsense-instead-simply steps 4 and 5.

is it not creating the shortcut in the startup folder? or is it just not starting up on a reboot even though it's in the startup folder?

> Installing SickGear
> Many systems (incl. mine) have Python already installed (mine into a path other than C:\Python27) and available via the system environment path. But this is completely ignored by the current choco package installer, this is all kinds of bad. In particular... a) existing Python installed applications and their respective deps get broken, and b) the Add/Remove Programs Uninstall for the pre-existing Python is destroyed.
> Ok, that's the bad, now, an idea on how to move forward... Instead of using the sickgear.nuspec dependencies entity, can python and git be moved into the chocolateyInstall.ps1 file so that logic capability to find installed versions linked to a conditional install can be achieved. The SickGear.lnk desktop shortcut Target and Start in fields would be created with the path to potential existing Python - provided that the version of the existing python is 2.7.9 or higher and less than 3.0 (having this logic will also make things easier to manage when SG becomes Python3 compatible) -- and if version condition is not satisfied, then the known dependency can then be fetched (bandwidth saved) and installed as default.

Sadly this isn't something that is allowed when putting packages on chocolatey.org as noted here https://github.com/chocolatey/choco/wiki/CreatePackages#rules-to-be-observed-before-publishing-packages at 8

> Don't include other required software if there's a package of it. If a package requires other software of which there is already a package, the already existing package should be used as dependency instead.

So since both python and git already exist as packages on chocolatey.org, they need to be included as dependencies in the .nuspec.

**Comment by JackDandy** [comment]
@JourneyOver 

Okay, let's pause on the windows start up, this other issue now has center stage...

> Don't include other required software if there's a package of it.

My proposal does not suggest to **include** other required software. 

I suggested to use existing choco packages but instead of using the choco dependency install flow via the xml entity in the nuspec, to **instead** wrap those deps in a condition under our finer control in the ps1 file... where we determine current user installed deps and prevent overwriting those,  but still use the existing choco maintained packages where applicable to the conditions I set out above. 

Are you saying choco does not permit this ? I can sure do it in ISS etc.

**Comment by JourneyOver** [comment]
@JackDandy 	

> My proposal does not suggest to include other required software.
> 
> I suggested to use existing choco packages but instead of using the choco dependency install flow via the xml entity in the nuspec, to instead wrap those deps in a condition under our finer control in the ps1 file... where we determine current user installed deps and prevent overwriting those, but still use the existing choco maintained packages where applicable to the conditions I set out above.

I know and get what you mean, but sadly choco does not permit doing such a thing, as any type of dependencies that are required; are required to be in the .nuspec and can not be set up in the .ps1 files otherwise I would.

Only options i see right now are:

1. Don't push to chocolatey, but instead I can look into doing MyGet instead for this sickgear, it'll still be installable through chocolatey but instead of pulling the source from chocolatey.org it'll be pulled from MyGet and we can set things up how ever we want and please.

(big problem with this idk if MyGet has a free variant or not as when I look on their site all I see are paid options, but it's supposedly "freemium")

or 

2. We figure out a way to bundle and make sickgear use a portable python and git which idk if it's even possible as I haven't looked into if there are ways to have a portable python and git (which then removes the whole dependency thing).

**Comment by JackDandy** [comment]
> Don't push to chocolatey, 

Agreed, we should put a hold on this. It is such a shame that it came down to this, but we cannot compromise on the very first introductory step into SickGear that is the installer.  

I did actually start creating an ISS installer that was doing exactly what I propose but stalled some time after the new year, I'll continue and complete that solution.

I am so very grateful for your time on this, thank you!

**Comment by JourneyOver** [comment]
@JackDandy 

> Agreed, we should put a hold on this. It is such a shame that it came down to this, but we cannot compromise on the very first introductory step into SickGear that is the installer.
> 
> I did actually start creating an ISS installer that was doing exactly what I propose but stalled some time after the new year, I'll continue and complete that solution.

Alright I'll put it on hold until further notice then.

if you can get an ISS installer setup and going fully that does git/python checks and all that kinda jazz like what you was wanting along with it of course installing sickgear and everything else it needs to do, I will be able to just use that instead of doing things the way we are now and I would be able to remove the dependencies due to the ISS installer taking care of said dependencies on it's own (ontop of mainly just cleaning up the installer .ps1 script as well since I won't need to make directories or do pip install stuff and shortcut stuff that can all be taken care of with the ISS installer xD).

Just let me know whenever you finish it up and I will go about making the changes on my side of things that need to be done ^^

Main thing I would like to see in the ISS installer of course is a way to do silent install/uninstall as I just prefer silent installs over needing to set up ahk and making a script to go through the install process (and it's the prefered way inside of chocolatey as well).

> I am so very grateful for your time on this, thank you!

It's not a problem at all, even if it did take a lot longer than expected to actually get around to working on this due to both my computer being broken when you actually requested this, and then when I actually have a computer again and had time to start working on things my mom ended up killing herself (which I'm still dealing with but have to find ways to keep myself pre-occupied)

**Comment by JourneyOver** [comment]
@JackDandy 	Hey man, just checking in and seeing how things are going with finishing up the installer so I can go about switching the sickgear chocolatey package up to use it instead, and merge it into the repository so it can start pushing up to chocolatey.

**Comment by JackDandy** [comment]
@JourneyOver Hi, I haven't got around to completing this yet and I wouldn't want to hold up an open issue or PR at your end, so by all means close it for now and we can maybe resume at a later point.

**Comment by JourneyOver** [comment]
Going to go ahead and close my issue/PR for now, if you ever want me to pick this back up again let me know.
